FROM nlcgi/jdk

RUN curl -Ls http://restx.io/install.sh | sh
RUN restx shell install io.restx:restx-core-shell:0.34
RUN restx shell install io.restx:restx-build-shell:0.34
RUN restx shell install io.restx:restx-specs-shell:0.34

